# Generated by Django 2.2.1 on 2019-06-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_changes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_currency',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_par',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_percent',
        ),
    ]
