# Generated by Django 2.2.1 on 2019-06-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_auto_20190617_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Followers',
            },
        ),
    ]
